#!/bin/bash

rm -rf cmake-build-debug
rm -rf cmake-build-debug-event-trace/

for x in `find . -name CMakeFiles -type d`; do
    rm -rf $x
done

for x in `find . -name Makefile`; do
    rm -f $x
done

for x in `find . -name cmake_install.cmake`; do
    rm -f $x
done

for x in `find . -name CMakeCache.txt`; do
    rm -f $x
done

